chucho/chucho/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from chucho import settings

from chucho import views

from .views import handler404, handler500, modificar_gasto, modificar_cita, modificar_examen, modificar_tratamiento, modificar_terapia, modificar_cirugia
from .views import eliminar_gasto, eliminar_cita, eliminar_examen, eliminar_tratamiento, eliminar_terapia, eliminar_cirugia

urlpatterns = [
    
## app imports

    path('', include('core.urls')),

### Admin ###
    path('', views.index, name='index'),
    path('admin/', admin.site.urls, name='admin:index'),
    path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),

### Lamigo ###
    path('registro/', views.registro, name='registro'),
    path('login2/', views.logeo, name='login2'),
    path('seccion_mascota/', views.seccion_mascota, name='seccion_mascota'),
    path('logout', views.logut_staff, name='logut'),

    # Mascota
    path('mascota/', views.mascota_view, name='mascota'),
    path('gastos/', views.gastos_view, name='gastos'),
    path('citas/', views.citas_view, name='citas'),
    path('examenes/', views.examenes_view, name='examenes'),
    path('tratamientos/', views.tratamientos_view, name='tratamientos'),
    path('terapias/', views.terapias_view, name='terapias'),
    path('cirugias/', views.cirugias_view, name='cirugias'),
    
    #Blog
    path('blog', views.blog, name='blog'),
    path('blog/sobre-nosotros', views.nosotros, name='nosotros'),
    path('blog/actualizaciones', views.actualizaciones, name='actualizaciones'),
    path('blog/arreglos', views.arreglos, name='arreglos'),
    path('blog/avisos', views.avisos, name='avisos'),
    path('blog/politicas', views.politicas, name='politicas'),
    path('blog/preguntas', views.preguntas, name='preguntas'),
    path('blog/servicios', views.servicios, name='servicios'),
    
    #Soportes y contacto
    path('contacto/', views.contacto, name='contacto'),
    path('soporte-tecnico/', views.soporte_tecnico, name='soporte'),
    path('informes-errores/', views.informes_errores, name='informes'),
    
    #Historial CRUD
    path('historial/', views.historial, name='historial'),
    ## CRUD EDIT ##
    # modificacion
    path('modificar_gasto/<int:id>/', modificar_gasto, name='modificar_gasto'),
    path('modificar_cita/<int:id>/', modificar_cita, name='modificar_cita'),
    path('modificar_examen/<int:id>/', modificar_examen, name='modificar_examen'),
    path('modificar_tratamiento/<int:id>/', modificar_tratamiento, name='modificar_tratamiento'),
    path('modificar_terapia/<int:id>/', modificar_terapia, name='modificar_terapia'),
    path('modificar_cirugia/<int:id>/', modificar_cirugia, name='modificar_cirugia'),
    
    #eliminacion
    path('eliminar_gasto/<int:id>/', eliminar_gasto, name='eliminar_gasto'),
    path('eliminar_cita/<int:id>/', eliminar_cita, name='eliminar_cita'),
    path('eliminar_examen/<int:id>/', eliminar_examen, name='eliminar_examen'),
    path('eliminar_tratamiento/<int:id>/', eliminar_tratamiento, name='eliminar_tratamiento'),
    path('eliminar_terapia/<int:id>/', eliminar_terapia, name='eliminar_terapia'),
    path('eliminar_cirugia/<int:id>/', eliminar_cirugia, name='eliminar_cirugia'),
    
    


    
    
    
]


chucho/core/urls.py
from django.urls import path

chucho/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User

from .choices import TYPES_DISEASES, TYPES_CITES, TYPES_BILLS, TYPES_SURGERYS, TYPES_EXAMNS

class mascota(models.Model):
    id = models.AutoField(primary_key=True)
    nombre_mascota = models.CharField(max_length=12)
    tipos = models.CharField(max_length=64)
    raza = models.CharField(max_length=32)
    sexo = models.CharField(max_length=10)
    edad = models.CharField(max_length=10)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre_mascota

    class Meta:
        ordering = ['id']

class citas(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=12)
    tipos = models.CharField(max_length=64)
    fecha = models.DateField()
    costo = models.FloatField()
    mascota = models.ForeignKey(mascota, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ['id']


class examenes(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=12)
    tipos = models.CharField(max_length=64)
    costo = models.FloatField()
    diagnosticos= models.CharField(max_length=512, verbose_name="diagnosticos")
    fecha = models.DateField()
    mascota = models.ForeignKey(mascota, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ['id']

class tratamientos(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=12)
    fecha = models.DateField()
    costo = models.FloatField()
    mascota = models.ForeignKey(mascota, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ['id']

class terapias(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=12)
    fecha = models.DateField()
    costo = models.FloatField()
    mascota = models.ForeignKey(mascota, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ['id']
    
class cirugias(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=12)
    tipos = models.CharField(max_length=64)
    fecha = models.DateField()
    costo = models.FloatField()
    mascota = models.ForeignKey(mascota, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ['id']
        
class gastos(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=12)
    tipos = models.CharField(max_length=64)
    fecha = models.DateField()
    costo = models.FloatField()
    mascota = models.ForeignKey(mascota, on_delete=models.CASCADE)
    
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return self.nombre

    class Meta:
        ordering = ['id']




chucho/chucho/forms.py
from dataclasses import field, fields
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView
from core.choices import GENDER_CHOICES
from django.core.exceptions import ValidationError

## crispy-forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from crispy_forms.bootstrap import FormActions
from django import forms
from core.models import gastos, citas, examenes, tratamientos, terapias, cirugias

##################### Usuario Forms ###########################

## Creacion de Cuenta

class UserRegisterForm(UserCreationForm):
    genero = forms.ChoiceField(
        choices=GENDER_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control'}),
    )
    username = forms.CharField(label="Nombre",widget=forms.TextInput(attrs={'placeholder': 'Tu Nombre'}))
    last_name = forms.CharField(label="Apellido",widget=forms.TextInput(attrs={'placeholder': 'Tu Apellido'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Correo electrónico'}))
    age = forms.IntegerField(widget=forms.NumberInput(attrs={'placeholder': 'Edad'}))
    password1 = forms.CharField(label="Contraseña",widget=forms.PasswordInput(attrs={'placeholder': 'Contraseña'}))
    password2 = forms.CharField(label="Confirmar contraseña",widget=forms.PasswordInput(attrs={'placeholder': 'Confirmar contraseña'}))

    class Meta:
        model = User
        fields = [
            'username',
            'last_name',
            'genero',
            'age',
            'email',
            'password1',
            'password2',
        ]

        help_texts = {k: "" for k in fields}

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError('Este correo electrónico ya está registrado. Por favor, usa otro.')
        return email
        
## Inicio de sesion

class LoginForm(forms.Form):
    username = forms.CharField()
    email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


##Contacto

class formcontact(forms.Form):

    asunto=forms.CharField(min_length=8, max_length=24)
    email=forms.EmailField()
    mensaje=forms.CharField(min_length=32, max_length=512)
    
##Soporte

class formsoporte(forms.Form):

    asunto=forms.CharField(min_length=8, max_length=24)
    email=forms.EmailField()
    mensaje=forms.CharField(min_length=32, max_length=512)
    
##Informes de errores

class forminformes(forms.Form):

    asunto=forms.CharField(min_length=8, max_length=24)
    email=forms.EmailField()
    mensaje=forms.CharField(min_length=32, max_length=512)

#Historiales

#Gastos
class GastoForm(forms.ModelForm):
    class Meta:
        model = gastos
        fields = ['nombre', 'tipos', 'fecha', 'costo', 'mascota']

#Citas
class CitasForm(forms.ModelForm):
    class Meta:
        model = citas
        fields = ['nombre', 'tipos', 'fecha', 'costo', 'mascota']
        
#Examenes
class ExamenesForm(forms.ModelForm):
    class Meta:
        model = examenes
        fields = ['nombre', 'tipos', 'fecha', 'costo', 'mascota']
        
#Tratamientos 
class TratamientosForm(forms.ModelForm):
    class Meta:
        model = tratamientos
        fields = ['nombre', 'fecha', 'costo', 'mascota']
        
#Terapias
class TerapiasForm(forms.ModelForm):
    class Meta:
        model = terapias
        fields = ['nombre', 'fecha', 'costo', 'mascota']
        
#Cirugias
class CirugiasForm(forms.ModelForm):
    class Meta:
        model = cirugias
        fields = ['nombre', 'tipos', 'fecha', 'costo', 'mascota']                       

chucho/templates/blog-actualizaciones.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kalnia&display=swap" rel="stylesheet">
    <!--iconos awesome fonts-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/blog-actualizaciones.css' %}">
    <title>Actualizaciones</title>
</head>
<body>
    <header>
        <nav>
            <input type="checkbox" id="ckbox">
            <label for="ckbox" class="drawer">
                <i class="fa fa-bars" aria-hidden="true"></i>
            </label>
            <h1>L'AMIGO</h1>
            <ul class="menu-box">
                {% if user.is_authenticated and not user.is_staff %}
                <li><a href="{% url 'index' %}">Inicio</a></li>
                <li><a href="{% url 'seccion_mascota' %}" id="amigo">Amigo</a></li>
                <li><a href="{% url 'blog' %}">Blog</a></li>
                <li><a href="{% url 'contacto' %}">Contacto</a></li>
                <li><a href="{% url 'servicios' %}">Servicios</a></li>
                <li><a href="{% url 'soporte' %}">Soporte</a></li>     
                <li><a href="{% url 'logout' %}">Cerrar sesión</a></li>
                {% else %}
                    <li><a href="{% url 'index' %}">Inicio</a></li>   
                    <li><a href="{% url 'login2' %}">Iniciar sesión</a></li>
                    <li><a href="{% url 'registro' %}">Registrarse</a></li>
                    <li><a href="{% url 'blog' %}">Blog</a></li>
                    <li><a href="{% url 'contacto' %}">Contacto</a></li>
                    <li><a href="{% url 'servicios' %}">Servicios</a></li>
                    <li><a href="{% url 'soporte' %}">Soporte</a></li>                
                {% endif %}

            </ul>
        </nav>
    </header>

    <div class="container-cover">
        <div class="container-cover-info">
            <h1>Actualizaciones</h1>
            <H2>Enterate de las ultimas novedades de L'amigo</H2>
        </div>
    </div>

    <div class="container-content">
        <article>
            <h1>Muy Pronto</h1>
            <p>
                ¡¡Nada aun!!
            </p>

            <h1>Muy Pronto</h1>
            <p>
                !!Nada aun¡¡
            </p>

            <h1>Muy Pronto</h1>
            <p>
                ¡¡Nada aun!!
            </p>

            <h1>Muy Pronto</h1>
            <p>
                !!Nada aun¡¡
            </p>

            <h1>Muy Pronto</h1>
            <p>
                ¡¡Nada aun!!
            </p>

            <h1>Muy Pronto</h1>
            <p>
                !!Nada aun¡¡
            </p>

        </article>
    
        <div class="container-aside">

            <aside>
                <img src="{% static 'blog/aside-consejos.jpg' %}" alt="">
                <h2>Consejos</h2>
                <p>
                    Aqui se te indicara las instrucciones
                    de la app.
                </p>
                <a href=""><button>Leer Más</button></a>
            </aside>

            <aside>
                <img src="{% static 'blog/aside-noticias.jpg' %}" alt="">
                <h2>Noticias</h2>
                <p>
                    Enterate sobre las ultimas novedades
                    de Lamigo.
                </p>
                <a href=""><button>Leer Más</button></a>
            </aside>

            <aside>
                <img src="{% static 'blog/aside-actualizaciones.jpg' %}" alt="">
                <h2>Actualizaciones</h2>
                <p>
                    Enterate sobre las ultimas Actualizaciones
                    y contenido agregado.
                </p>
                <a href=""><button>Leer Más</button></a>
            </aside>

            <aside>
                <img src="{% static 'blog/aside-cambios.jpg' %}" alt="">
                <h2>Historial de cambios</h2>
                <p>
                    Informate de todos los cambios que ha
                    tenido Lamigo.
                </p>
                <a href=""><button>Leer Más</button></a>
            </aside>

        </div>

    </div>

    <!--Sobre Nosotros-->

    <section id="blog">
        <div class="blog-heading">
            <h3>L'AMIGO</h3>
        </div>
    </section>

    <div class="blog-container">

        <div class="blog-box">
            <div class="blog-img">
                <img src="{% static 'blog/about-about.jpg' %}" alt="">
            </div>

            <div class="blog-text">
                <a href="#" class="blog-title">¿Quienes Somos?</a>
                <p>
                    Lamigo se especializa en ofrecer una plataforma web única 
                    diseñada para simplificar y potenciar la gestión de la 
                    información crucial de tus mascotas. Nuestra pasión 
                    por el cuidado de los animales impulsa nuestro compromiso 
                    de motivar y respaldar a los dueños de mascotas.
                </p>
                <a href="{% url 'nosotros' %}">Leer mas</a>
            </div>
        </div>

        <div class="blog-box">
            <div class="blog-img">
                <img src="{% static 'blog/about-trabajo.jpg' %}" alt="">
            </div>

            <div class="blog-text">
                <a href="#" class="blog-title">Trabaja con Nosotros</a>
                <p>
                    Comunicate con Nosotros para aplicar a vacantes
                </p>
                <a href="#">Leer mas</a>
            </div>
        </div>

        <div class="blog-box">
            <div class="blog-img">
                <img src="{% static 'blog/about-contacto.jpg' %}" alt="">
            </div>

            <div class="blog-text">
                <a href="#" class="blog-title">Contactanos</a>
                <p>
                    Nos puedes escribir para sugerencias o reportes
                    de errores que haya en la plataforma
                </p>
                <a href="{% url 'contacto' %}">Leer mas</a>
            </div>
        </div>

    </div>

    <footer class="footer">
        <div class="container">
            <div class="footer-row">
                <div class="footer-links">
                    <h4>Compañia</h4>
                    <ul>
                        <li><a href="{% url 'nosotros' %}">Nosotros</a></li>
                        <li><a href="{% url 'servicios' %}">Nuestros servicios</a></li>
                        <li><a href="{% url 'politicas' %}">Politicas de privacidad</a></li>
                    </ul>
                </div>
                <div class="footer-links">
                    <h4>Ayuda</h4>
                    <ul>
                        <li><a href="{% url 'preguntas' %}">Preguntas</a></li>
                        <li><a href="{% url 'soporte' %}">Soporte Tecnico</a></li>
                        <li><a href="{% url 'informes' %}">Reporte de fallas</a></li>
                    </ul>
                </div>
                <div class="footer-links">
                    <h4>Noticias</h4>
                    <ul>
                        <li><a href="{% url 'avisos' %}">Avisos</a></li>
                        <li><a href="{% url 'actualizaciones' %}">Actualizaciones</a></li>
                        <li><a href="{% url 'arreglos' %}">Arreglos</a></li>
                    </ul>
                </div>
                <div class="footer-links">
                    <h4>Apoyanos</h4>
                    <div class="social-links">
                        <a href="https://www.youtube.com/@Lamigo2023" target="_blank" id="youtube"><i id="youtube" class="fab fa-youtube"></i></a>
                        <a href="https://twitter.com/Lamigo0010" target="_blank" id="twitter"><i class="fab fa-twitter"></i></a>
                        <a href="https://www.patreon.com/Lamigo" target="_blank" id="patreon"><i class="fab fa-patreon"></i></a>
                    </div>
                </div>

                <div>
                    
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

<!--Ya-->

chucho/templates/examenes.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/examenes.css' %}">
</head>
<body>
    <div class="form-container">
        <form method="post" action="{% url 'examenes' %}">

            {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'error' %}
                    <div class="alert error">
                        {{ message }}
                    </div>
                {% endif %}
                {% endfor %}
            {% endif %}

                {% csrf_token %}

                <label for="id_mascota">Seleccione la mascota:</label>
                <select id="id_mascota" name="mascota" required>
                    {% for mascota in user_pets %}
                        <option value="{{ mascota.id }}">{{ mascota.nombre_mascota }}</option>
                    {% endfor %}
                </select><br>           

                <label for="id_tipos">Tipo de examen:</label>
                <select id="id_tipos" name="tipos" required>
                {% for choice in TYPES_EXAMNS %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
                </select><br>

                <label for="id_nombre">Nombre:</label><br><br>
                <input type="text" id="id_nombre" name="nombre" required><br><br>

                <label for="id_fecha">Fecha de programacion:</label><br><br>
                <input type="date" id="id_fecha" name="fecha" required><br><br>

                <label for="id_costo">Costo:</label><br>
                <input type="number" id="id_costo" name="costo" required>
                
                <button type="submit" class="btn">Registrar Examen</button>

            </form>
        </form> 
    </div>
</body>
</html>

chucho/templates/gastos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/gastos.css' %}">
</head>
<body>
    <div class="form-container">
        <form method="post" action="{% url 'gastos' %}">

            {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'error' %}
                    <div class="alert error">
                        {{ message }}
                    </div>
                {% endif %}
                {% endfor %}
            {% endif %}

                {% csrf_token %}

                <label for="id_mascota">Seleccione la mascota:</label>
                <select id="id_mascota" name="mascota" required>
                    {% for mascota in user_pets %}
                        <option value="{{ mascota.id }}">{{ mascota.nombre_mascota }}</option>
                    {% endfor %}
                </select><br>          
                
                <label for="id_tipos">Tipo de gasto:</label>
                <select id="id_tipos" name="tipos" required>
                {% for choice in TYPES_BILLS %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
                </select><br>

                <label for="id_nombre">Nombre:</label><br><br>
                <input type="text" id="id_nombre" name="nombre" required><br><br>

                <label for="id_fecha">Fecha de programacion:</label><br><br>
                <input type="date" id="id_fecha" name="fecha" required><br><br>

                <label for="id_costo">Costo:</label><br>
                <input type="number" id="id_costo" name="costo" required>
                
                <button type="submit" class="btn">Registrar Gasto</button>

            </form>
        </form> 
    </div>
</body>
</html>

chucho/templates/gestionar_gastos.html
<!--gestionar_gastos-->
<div class="history-container">
    <div class="boxes">
        <h2>Gastos</h2>

        {% if user_bills %}
            <ul>
                {% for bill in user_bills %}
                    <li>
                        <div class="bills">
                            Nombre: {{ bill.nombre }}
                        </div>

                        <div class="bills">
                            Tipo: {{ bill.tipos }}
                        </div>

                        <div class="bills">
                            Fecha: {{ bill.fecha }} 
                        </div>

                        <div class="bills">
                            Costo: {{ bill.costo }}
                        </div><br>

                        <div class="bills">
                            Mascota: {{ bill.mascota.nombre_mascota }}
                        </div>

                        <div class="center-container">
                            <a href="{% url 'editar_gasto' bill.id %}" class="edit-link">Editar Gasto</a>
                            <a href="{% url 'eliminar_gasto' bill.id %}" class="delete-link">Eliminar Gasto</a>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="descripcion-nula">No hay registros de gastos.</p>
        {% endif %}
    </div>
</div>

<script>
    // Agregar funciones JavaScript para manejar la selección, edición y eliminación
    document.querySelectorAll('.edit-link').forEach(link => {
        link.addEventListener('click', function (e) {
            e.preventDefault();
            // Agregar lógica para editar el registro con el ID correspondiente
            alert('Editar: ' + this.getAttribute('href'));
        });
    });

    document.querySelectorAll('.delete-link').forEach(link => {
        link.addEventListener('click', function (e) {
            e.preventDefault();
            // Agregar lógica para eliminar el registro con el ID correspondiente
            alert('Eliminar: ' + this.getAttribute('href'));
        });
    });
</script>

chucho/templates/lista_gastos.html
<!-- lista_gastos.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Gastos</title>
</head>
<body>
    <h2>Lista de Gastos</h2>
    <ul>
        {% for gasto in gastos_list %}
        <div>
          <p>{{ gasto.nombre }} - {{ gasto.costo }}</p>
          <button class="editar-gasto-btn" data-gasto-id="{{ gasto.id }}">Editar</button>
          <button class="eliminar-gasto-btn" data-gasto-id="{{ gasto.id }}">Eliminar</button>
        </div>
        {% endfor %}
    </ul>
</body>
</html>

chucho/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <title>Inicio de sesión</title>
</head>
<body>
    {% if form.errors %}
    <div class="error-message">
        <strong>Por favor, corrige los siguientes errores:</strong>
        <ul>
            {% for field, errors in form.errors.items %}
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>
    {% endif %}
    <div class="container">
        <h1>Inicio de sesión</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form }}<br>
            <a href="{% url 'registro' %}">No tienes cuenta?</a>
            <!--<a href="">Restablecer contraseña</a>-->
            <button id="submit-btn" type="submit">Login</button>
        </form>
    </div>
</body>
</html>

chucho/templates/soporte-tecnico.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/soporte-tecnico.css' %}">
    <style>

    </style>
    <title>Contacto</title>
</head>
<body>
    <div class="form-container">
        <form class="mascota-form" method="post">

            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'error' %}
                        <div class="alert error">
                            {{ message }}
                        </div>
                    {% else %}
                        <div class="alert success">
                            {{ messages }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}

            {% csrf_token %}

            <h1 class="form-header">Soporte Tecnico</h1>

            <label for="id_asunto">Asunto:</label>
            <input type="text" id="id_asunto" name="asunto" placeholder="Asunto" required>

            <label for="id_mensaje">Mensaje:</label>
            <textarea id="id_mensaje" name="mensaje" placeholder="Escribe tu mensaje aquí" required></textarea>

            <label for="id_email">Email:</label>
            <input type="text" id="id_email" name="email" placeholder="Tu correo electrónico" required>

            <button type="submit" class="btn">Enviar</button>
        </form>
    </div>
</body>
</html>

chucho/templates/tratamientos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/tratamientos.css' %}">
</head>
<body>
    <div class="form-container">
        <form method="post" action="{% url 'tratamientos' %}">

            {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'error' %}
                    <div class="alert error">
                        {{ message }}
                    </div>
                {% endif %}
            {% endfor %}
            {% endif %}

                {% csrf_token %}

                <label for="id_mascota">Seleccione la mascota:</label>
                <select id="id_mascota" name="mascota" required>
                    {% for mascota in user_pets %}
                        <option value="{{ mascota.id }}">{{ mascota.nombre_mascota }}</option>
                    {% endfor %}
                </select><br>              

                <label for="id_nombre">Nombre:</label><br><br>
                <input type="text" id="id_nombre" name="nombre" required><br><br>

                <label for="id_fecha">Fecha de programacion:</label><br><br>
                <input type="date" id="id_fecha" name="fecha" required><br><br>

                <label for="id_costo">Costo:</label><br>
                <input type="number" id="id_costo" name="costo" required>
                
                <button type="submit" class="btn">Registrar Tratamiento</button>

            </form>
        </form> 
    </div>
</body>
</html>